[Populate Splunk Users Collection]
search = | rest /services/authentication/users\
| search email != ""\
| fields title email roles realname\
| rename title AS splunk_username email AS splunk_email roles AS splunk_roles realname AS splunk_realname\
| sort splunk_email\
| outputlookup rqst_kv_users
