[default]

[install]
is_configured = 0
install_source_checksum = 5bfcb743a330f05b389a86c476ecbd474d8e9e68

[launcher]
author = RedFactor, LLC
version = 1.5.0
description = rqst provides Splunk data request management

[package]
check_for_updates = 0
id = rqst

[ui]
label = rqst Data Ops
is_visible = 1

