[rqst_data]
enforceTypes = false
field.data_id = number
field.origin = string
field.timestamp = timestamp
field.status = string
field.priority = string
field.due_date = timestamp
field.use_case = string
field.data_tags = string
field.data_description = string
field.data_group_access = string
field.data_volume = number
field.data_transport = string
field.data_hostnames = string
field.data_sample = string
field.notes = string
field.admin_sourcetype = string
field.admin_index = string
field.admin_user = string
field.requestor_user = string
field.requestor_realname = string
field.requestor_email = string
field.custom_field = string

[rqst_options]
enforceTypes = true
field.priority = string
field.status = string
field.use_case = string
field.data_transport = string
field.indexer_daily_ingest_target = number
field.cost_per_license_gb = double
field.cost_per_indexer = double
field.cost_per_tb_storage = double
field.approval_process = string
field.email_new_request_user = string
field.email_new_request_approver = string
field.email_new_request_admin = string
field.email_updated_request_user = string
field.email_server = string
field.email_notifications = string
field.replication_factor = number
field.search_factor = number
field.help_url = string
field.show_custom_field = string
field.custom_field_label = string
field.custom_field_values = string
field.custom_field_description = string
field.kvkit_server = string

[rqst_audit]
enforceTypes = true
field.timestamp = time
field.data_id = number
field.user = string
field.action_type = string
field.action_detail = string

[rqst_team]
enforceTypes = true
field.admin_user = string
field.admin_title = string
field.admin_realname = string
field.admin_phone = string
field.admin_email = string
field.admin_approver = bool
field.admin_rqst_owner = bool

[rqst_journal]
enforceTypes = true
field.timestamp = time
field.data_id = number
field.admin_user = string
field.entry = string

[rqst_groups]
enforceTypes = true
field.splunk_role = string
field.group_alias = string

[rqst_users]
enforceTypes = true
field.splunk_username = string
field.splunk_email = string
field.splunk_roles = string
field.splunk_realname = string
