[Populate Groups Collection]
action.email.useNSSubject = 1
alert.track = 0
cron_schedule = 0 0 * * *
dispatch.earliest_time = 0
display.general.timeRangePicker.show = 0
display.general.type = statistics
display.page.search.mode = verbose
display.page.search.tab = statistics
display.visualizations.charting.chart.style = minimal
display.visualizations.custom.type = simple_xml_examples.tagcloud
display.visualizations.show = 0
request.ui_dispatch_app = rqst
request.ui_dispatch_view = search
search = | rest /services/authorization/roles \
| makemv roles\
| mvexpand roles\
| where NOT (title in("admin","can_delete","power","splunk-system-role","user","rqst_requestor","rqst_rest")) \
| dedup title \
| sort title \
| rename title AS splunk_role \
| eval group_alias = splunk_role \
| table splunk_role group_alias\
| outputlookup rqst_kv_groups

[Populate Splunk Users Collection]
action.email.useNSSubject = 1
alert.track = 0
cron_schedule = 0 0 * * *
dispatch.earliest_time = 0
display.general.timeRangePicker.show = 0
display.general.type = statistics
display.page.search.mode = verbose
display.page.search.tab = statistics
display.visualizations.charting.chart.style = minimal
display.visualizations.custom.type = simple_xml_examples.tagcloud
display.visualizations.show = 0
request.ui_dispatch_app = rqst
request.ui_dispatch_view = search
search = | rest /services/authentication/users\
| search email != ""\
| fields title email \
| rename title AS splunk_username email AS splunk_email roles AS splunk_roles realname AS splunk_realname\
| sort splunk_email\
| outputlookup rqst_kv_users

[Update Groups Collection]
action.email.useNSSubject = 1
alert.track = 0
dispatch.earliest_time = -24h@h
dispatch.latest_time = now
display.general.timeRangePicker.show = 0
display.general.type = statistics
display.page.search.tab = statistics
display.visualizations.show = 0
request.ui_dispatch_app = rqst
request.ui_dispatch_view = search
search = | rest /services/authorization/roles \
| makemv roles \
| mvexpand roles \
| dedup title \
| sort title \
| rename title AS splunk_role \
| eval group_alias = splunk_role \
| join type=left splunk_role [| inputlookup rqst_kv_groups | eval existing_role = splunk_role | table existing_role splunk_role] \
| where isnull(existing_role) \
| table splunk_role group_alias \
| outputlookup append=true rqst_kv_groups

