[settings]
dashboard_html_allow_embeddable_content = true
dashboard_html_allow_iframes = true
x_frame_options_sameorigin = false

[expose:create_request]
pattern=create_request
methods=POST

[expose:update_request]
pattern=update_request
methods=POST

